Loader component
AllmostHumann/movie-browser pull request #6
Opened 2023-03-24 09:07 UTC by PawelNackowski

Hi ! I created Loader :)

2023-03-24 10:35 UTC, AllmostHumann requested changes
I have no objections. 

Just let's use this convention for breakpoints ;)

`const mobileMinBp = ({ theme }) => theme.breakpoints.mobileMin;`

2023-03-24 10:44 UTC, alajurczak requested changes
I have a few comments :)

2023-03-24 10:44 UTC, alajurczak commented on src/Common/Loader/styled.js
I think "index.js" should also appear in the Loader folder. In index.js also add e.g. "Header" for displaying "Search results for "Mulan".

2023-03-24 10:44 UTC, alajurczak commented on src/Common/Loader/styled.js
> +     @media (max-width: ${({ theme }) => theme.breakpoints.mobileMin}px){
As Jakub said, it's worth using one convention about styling breakpoints.

2023-03-24 10:48 UTC, PawelNackowski commented on src/Common/Loader/styled.js
I think Loader is a separate component that can be used for loading posters, movie page, loading page, and other places. What do you think?

2023-03-24 10:51 UTC, PawelNackowski commented on src/Common/Loader/styled.js
> +     @media (max-width: ${({ theme }) => theme.breakpoints.mobileMin}px){
I forgot about that. I corrected it 😄

2023-03-24 11:13 UTC, AllmostHumann commented on src/Common/Loader/styled.js
Generally yes "Loader" should be a separate component, but index.js and styled.js I would do separately ;).

In index.js you could make a normal arrow function and make a component consisting of container, title and spinner.

Out of curiosity, why didn't you download the spinner graphic from the figma project?

2023-03-24 11:20 UTC, alajurczak commented on src/Common/Loader/styled.js
Yeah, that's what I meant. 
I think he did it right when it comes to spinner graphic :)

2023-03-24 11:22 UTC, PawelNackowski commented on src/Common/Loader/styled.js
I found it easier to adapt when it was made from scratch in CSS. 😀

2023-03-25 08:44 UTC, PawelNackowski commented
I created a loading page. Please check 😃

2023-03-25 08:55 UTC, alajurczak approved these changes
It looks greate :)

2023-03-25 09:00 UTC, AllmostHumann commented
Nothing to add for me 😉

2023-03-25 09:03 UTC, AllmostHumann approved these changes
Looking good to me top 😁

2023-03-25 09:19 UTC, merged