Movie list
AllmostHumann/movie-browser pull request #7
Opened 2023-03-24 10:41 UTC by AllmostHumann

Hey! 

I have prepared movie list for you webpage ;). I have updated my branch with changes what you made before, and I did some changes with better folders layout,  some cosmetic changes in styles and I also removed from GlobalStyles the " display: flex;" option because the Header component didn't display at whole screen. 

![image](https://user-images.githubusercontent.com/106307102/227500918-41146b82-a062-47fb-a5e9-7344d371dfef.png)

Cheers!

2023-03-24 18:14 UTC, alajurczak approved these changes

2023-03-24 18:14 UTC, alajurczak commented on src/features/movies/PopularMovies/index.js
Don't you think it should be index.js for the MovieList component? After that it doesn't have to be a component like PopularMovies.
If we are going to change it like this, MovieList should be in "feature".

2023-03-25 09:46 UTC, PawelNackowski requested changes
![pages](https://user-images.githubusercontent.com/117357734/227709740-12b90bba-f601-41f7-838f-67374a0f48be.png)

In the 100% view, the tiles diverge to 3. Maybe use scaling so that they are always 4 and with a lower resolution, less?

2023-03-25 14:24 UTC, AllmostHumann commented
> ![pages](https://user-images.githubusercontent.com/117357734/227709740-12b90bba-f601-41f7-838f-67374a0f48be.png)
> 
> In the 100% view, the tiles diverge to 3. Maybe use scaling so that they are always 4 and with a lower resolution, less?

2023-03-25 14:28 UTC, AllmostHumann commented
> ![pages](https://user-images.githubusercontent.com/117357734/227709740-12b90bba-f601-41f7-838f-67374a0f48be.png)
> 
> In the 100% view, the tiles diverge to 3. Maybe use scaling so that they are always 4 and with a lower resolution, less?

Hey @PawelNackowski. I know there coudl be an issue with display the movie tiles. I made this kind of list made of a lot of <li> components just to show how it looks. When we implement API for movies it shoudl looks much better. Sorry I didn't let you know earlier about that. But if you want I can try to change this display right now.

2023-03-25 14:31 UTC, PawelNackowski commented
It's ok. We'll fix it later.

2023-03-25 14:32 UTC, PawelNackowski commented
> > ![pages](https://user-images.githubusercontent.com/117357734/227709740-12b90bba-f601-41f7-838f-67374a0f48be.png)
> > 
> > In the 100% view, the tiles diverge to 3. Maybe use scaling so that they are always 4 and with a lower resolution, less?
> 
> Hey @PawelNackowski. I know there coudl be an issue with display the movie tiles. I made this kind of list made of a lot of <li> components just to show how it looks. When we implement API for movies it shoudl looks much better. Sorry I didn't let you know earlier about that. But if you want I can try to change this display right now. 

It's ok. We'll fix it later.

2023-03-25 14:34 UTC, AllmostHumann commented
> > > ![pages](https://user-images.githubusercontent.com/117357734/227709740-12b90bba-f601-41f7-838f-67374a0f48be.png)
> > > In the 100% view, the tiles diverge to 3. Maybe use scaling so that they are always 4 and with a lower resolution, less?
> > 
> > 
> > Hey @PawelNackowski. I know there coudl be an issue with display the movie tiles. I made this kind of list made of a lot of * components just to show how it looks. When we implement API for movies it shoudl looks much better. Sorry I didn't let you know earlier about that. But if you want I can try to change this display right now.
> 
> It's ok. We'll fix it later.

OK, perfect ;) I also implemetn @alajurczak  Pagination in my branch. So, if you agreed please approve my pull and I will merge it to main branch asap ;).

2023-03-25 14:35 UTC, PawelNackowski approved these changes

2023-03-25 14:36 UTC, merged